import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body className={inter.className + 'h-screen w-screen flex flex-col'}>
				{/* <div className="inline-flex">
					<Link href="/admin">Admin</Link>
					<Link href="/auth/login">login</Link>
					<Link href="/business">Admin</Link>
					<Link href="/">home</Link>
				</div> */}
				<MantineProvider defaultColorScheme="dark">{children}</MantineProvider>
			</body>
		</html>
	);
}
